services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=codmind
      - MYSQL_PASSWORD=1234
    ports:
      - 3306:3306
    networks:
      - wordpress-net
  wordpress:
    image: wordpress
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - wordpress-net
    ports:
      - 8080:80
networks:
  wordpress-net: